export const config = {
  gitHubUser: 'gowdasagar06',
  gitHubRepo: 'hello-world-mvn-java',
  gitHubBranch: 'main',
  codeArtifactRepository: 'matson',
  codeBuildEnvironmentType: 'LINUX_CONTAINER',
  codeBuildComputeType: 'BUILD_GENERAL1_SMALL',
  codeBuildImage: 'aws/codebuild/amazonlinux2-x86_64-standard:5.0',
  labAccountId: '275416279984',
  devAccountId: '440476207545',
  preprodAccountId: '163355195061',
  prodAccountId: '689838003629',
  snsNotificationDisplayName: 'Matson-sns-for-manual-approval-notification',
  sourcestage: 'Source-stage',
  buildstage: 'Build-stage',
  saststage: 'SAST-stage',
  daststage: 'DAST-stage',
  labstage: 'Labs-stage',
  devstage: 'Dev-stage',
  preprodstage: 'Preprod-stage',
  prodstage: 'Prod-stage',
  approvalstagepp: 'Approval-stage-pp',
  approvalstageprod: 'Approval-stage-prod',
 codeStarConnectionArn: 'arn:aws:codestar-connections:ap-south-1:637423476845:connection/33f1dfb5-607b-447a-bf4c-a28325ee89e2',

  bucketLifecyclePolicy: {
    id: 'lifecycle-policy',
    status: 'Enabled',
    prefix: 'SourceArti/',
    transitionInDays: 30,
    expirationInDays: 300,
  },
  buildSpecs: {
    build: 'aws/infra/codepipeline/buildspec.yml',
    dev: 'buildspec-dev.yml',
    lab: 'buildspec-lab.yml',
    pp: 'buildspec-pp.yml',
    prod: 'buildspec-prod.yml',
    sast: 'buildspec-sast.yml', 
    dast: 'buildspec-dast.yml', 
  },

};
